version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - "${PWD}/data:/data/db"
    restart: always
#  rabbitmq:
#    container_name: rabbit-mq
#    image: rabbitmq: 3
#    ports:
#      - "5672:5672"
#    restart: always